// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://t4m57rgle5fcjanhan34ulop3i.appsync-api.ap-northeast-1.amazonaws.com/graphql',
          region: 'ap-northeast-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-b5pawi6i6fefxlloqji5quw3wa'
        }
    }
};

export default config;
