version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: risuwork
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-connections=2000
      - --innodb-buffer-pool-size=2G
      - --innodb-flush-log-at-trx-commit=0
      - --innodb-flush-method=O_DIRECT
      - --innodb-log-file-size=256M
      - --innodb-log-buffer-size=32M
      - --thread-cache-size=200
      - --table-open-cache=4000
      - --sort-buffer-size=4M
      - --read-buffer-size=4M
      - --join-buffer-size=8M
      - --innodb-read-io-threads=8
      - --innodb-write-io-threads=8
      - --innodb-redo-log-capacity=512M
      - --tmp-table-size=128M
      - --max-heap-table-size=128M
      - --slow-query-log=1
      - --slow-query-log-file=/var/log/mysql/slow.log
      - --long-query-time=0.1
      - --log-queries-not-using-indexes=1
      - --back_log=1000
      - --wait-timeout=60
      - --interactive-timeout=60
      - --net-read-timeout=30
      - --net-write-timeout=30
  java:
    build:
      context: ../../
      dockerfile: java/Dockerfile
    container_name: java_container
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - AWS_XRAY_TRACING_NAME=disabled
      - AWS_XRAY_CONTEXT_MISSING=LOG_ERROR
    depends_on:
      - mysql
  nginx:
    image: nginx:1.27
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - java
volumes:
  mysql_data:
