version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: risuwork
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-connections=3000
      - --innodb-buffer-pool-size=3G
      - --innodb-buffer-pool-instances=4
      - --innodb-flush-log-at-trx-commit=0
      - --innodb-flush-method=O_DIRECT
      - --innodb-log-file-size=512M
      - --innodb-log-buffer-size=64M
      - --thread-cache-size=500
      - --table-open-cache=8000
      - --table-open-cache-instances=16
      - --sort-buffer-size=8M
      - --read-buffer-size=4M
      - --read-rnd-buffer-size=8M
      - --join-buffer-size=16M
      - --innodb-read-io-threads=16
      - --innodb-write-io-threads=16
      - --innodb-io-capacity=4000
      - --innodb-io-capacity-max=8000
      - --innodb-redo-log-capacity=1G
      - --tmp-table-size=256M
      - --max-heap-table-size=256M
      - --slow-query-log=1
      - --slow-query-log-file=/var/log/mysql/mysql-slow.log
      - --long-query-time=0.1
      - --performance-schema=OFF
      - --skip-name-resolve
      - --back_log=1500
      - --innodb-autoinc-lock-mode=2
      - --innodb-doublewrite=0
  java:
    build:
      context: ../../
      dockerfile: java/Dockerfile
    container_name: java_container
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - AWS_XRAY_TRACING_NAME=disabled
      - AWS_XRAY_CONTEXT_MISSING=LOG_ERROR
      - JAVA_OPTS=-Xmx2g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AlwaysPreTouch -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=20 -XX:G1HeapRegionSize=32m -XX:+DisableExplicitGC
    depends_on:
      - mysql
  nginx:
    image: nginx:1.27
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - java
volumes:
  mysql_data:
