spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:risuwork}?useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useLocalSessionState=true&rewriteBatchedStatements=true&cacheResultSetMetadata=true&elideSetAutoCommits=true&maintainTimeStats=false&characterEncoding=UTF-8&useUnicode=true
    username: ${DB_USER:isucon}
    password: ${DB_PASS:isucon}
    hikari:
      maximum-pool-size: 1200
      minimum-idle: 200
      connection-timeout: 1000
      idle-timeout: 300000
      max-lifetime: 900000
      leak-detection-threshold: 30000
      validation-timeout: 2000
  jpa:
    open-in-view: false

server:
  port: 8080
  servlet:
    session:
      cookie:
        name: session
        http-only: true
        max-age: 3600
        path: /
        same-site: Strict

app:
  init-script-path: /home/isucon/webapp/sql/init.sh

logging:
  level:
    root: WARN
    jp.co.recruit: WARN
    org.springframework: WARN
    com.zaxxer.hikari: WARN
  pattern:
    console: "%msg%n"